default: &default
  adapter: postgresql
  encoding: unicode
  username: ''
  password: ''
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: db/beznatsenki_dev

test:
  <<: *default
  database: db/beznatsenki_test

production:
  <<: *default
  database: <%= ENV['POSTGRES_DB'] %>
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
